# .github/workflows/aggregate-data.yml
name: Aggregate Old Status Data

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight

jobs:
  aggregate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm ci
      - name: Aggregate Old Data
        run: node scripts/aggregate-data.js
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
